"""Base local administrable de preguntas frecuentes para CommuBot.

Cada entrada incluye pregunta principal, respuesta preparada, categoria,
palabras clave, variaciones, roles permitidos, estado de verificacion y
trazabilidad. La informacion especifica no confirmada se marca como pendiente
para que el asistente responda de forma segura sin inventar datos.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from typing import Iterable

from .taxonomy import get_main_intent_id, taxonomy_summary


ALL_ROLES = ("RESIDENTE", "VIGILANTE", "ADMINISTRADOR")
OPERATIVE_ROLES = ("VIGILANTE", "ADMINISTRADOR")
ADMIN_ROLE = ("ADMINISTRADOR",)
UPDATED_AT = "2026-06-05"
VERIFICATION_VERIFIED = "VERIFICADA"
VERIFICATION_PENDING_ADMIN = "PENDIENTE_VALIDACION_ADMINISTRACION"
VALIDITY_ACTIVE = "VIGENTE"
VALIDITY_EXPIRED = "VENCIDA"


@dataclass(frozen=True)
class FAQEntry:
    id: str
    intent: str
    category: str
    question: str
    answer: str
    keywords: tuple[str, ...]
    variations: tuple[str, ...]
    allowed_roles: tuple[str, ...] = ALL_ROLES
    verified: bool = True
    updated_at: str = UPDATED_AT
    valid_from: str = UPDATED_AT
    valid_until: str = ""
    maintainer_role: str = "ADMINISTRADOR"
    source: str = "Base de conocimiento local CommuSafe - Remansos del Norte"
    change_trace: tuple[str, ...] = (
        "2026-06-05: Entrada creada para motor hibrido local de CommuSafe.",
    )

    def searchable_texts(self) -> Iterable[str]:
        yield self.question
        yield from self.variations
        yield " ".join(self.keywords)

    @property
    def verification_status(self) -> str:
        return VERIFICATION_VERIFIED if self.verified else VERIFICATION_PENDING_ADMIN

    @property
    def main_intent(self) -> str:
        return get_main_intent_id(self.id)

    @property
    def validity_status(self) -> str:
        return VALIDITY_ACTIVE if self.is_active() else VALIDITY_EXPIRED

    def is_active(self, today: date | None = None) -> bool:
        if not self.valid_until:
            return True
        today = today or date.today()
        try:
            return today <= date.fromisoformat(self.valid_until)
        except ValueError:
            return False

    def to_dict(self) -> dict[str, object]:
        return {
            "id": self.id,
            "intent": self.main_intent,
            "main_intent": self.main_intent,
            "subintent": self.intent,
            "category": self.category,
            "question": self.question,
            "answer": self.answer,
            "keywords": self.keywords,
            "variations": self.variations,
            "allowed_roles": self.allowed_roles,
            "verified": self.verified,
            "verification_status": self.verification_status,
            "validity_status": self.validity_status,
            "valid_from": self.valid_from,
            "valid_until": self.valid_until,
            "updated_at": self.updated_at,
            "maintainer_role": self.maintainer_role,
            "source": self.source,
            "change_trace": self.change_trace,
        }


SAFE_ADMIN_CONTACT = (
    "No encuentro un dato exacto registrado en CommuSafe para esa consulta. "
    "Te recomiendo validarlo directamente con administracion para recibir la informacion actualizada."
)


FAQ_ENTRIES: tuple[FAQEntry, ...] = (
    FAQEntry(
        "uso_001",
        "iniciar_sesion",
        "uso_sistema",
        "Como inicio sesion en CommuSafe?",
        "Ingresa con el correo asignado y la contrasena entregada por administracion. Si el acceso falla, verifica que el correo este bien escrito y solicita apoyo a administracion para validar tu cuenta.",
        ("login", "sesion", "correo", "contrasena", "acceso", "cuenta", "entrar"),
        ("no puedo entrar", "no puedo entrar a la cuenta", "como ingreso", "con que correo entro", "me falla el login"),
    ),
    FAQEntry(
        "uso_002",
        "recuperar_acceso",
        "uso_sistema",
        "Que hago si olvide mi contrasena?",
        "Solicita apoyo a administracion para restablecer el acceso. En esta version el flujo visible de recuperacion esta deshabilitado porque las cuentas se gestionan internamente.",
        ("clave", "contrasena", "olvide", "recuperar", "acceso"),
        ("olvide mi clave", "no recuerdo mi contrasena", "perdi el acceso", "necesito cambiar la clave"),
    ),
    FAQEntry(
        "uso_003",
        "crear_incidente",
        "uso_sistema",
        "Como reporto un incidente?",
        "Desde la app entra a Incidentes, toca Nuevo, escribe un titulo claro, selecciona categoria, describe lo ocurrido, agrega ubicacion de referencia y adjunta hasta 3 fotos si las tienes. Luego toca Reportar incidente.",
        ("reportar", "incidente", "nuevo", "crear", "reporte"),
        ("como hago un reporte", "donde creo un incidente", "quiero reportar algo", "como subo una novedad"),
    ),
    FAQEntry(
        "uso_004",
        "consultar_estado_incidente",
        "uso_sistema",
        "Como veo el estado de mi reporte?",
        "Abre Incidentes y selecciona el caso. En el detalle veras el estado actual, la descripcion, las evidencias y el timeline de cambios con comentarios del responsable.",
        ("estado", "seguimiento", "historial", "reporte", "detalle"),
        ("como va mi caso", "donde veo el seguimiento", "quiero mirar mi reporte", "como se si ya atendieron"),
    ),
    FAQEntry(
        "uso_005",
        "adjuntar_evidencia",
        "uso_sistema",
        "Como adjunto fotos a un incidente?",
        "Al crear el incidente puedes usar camara o galeria para adjuntar evidencia fotografica. El sistema permite maximo 3 imagenes por reporte.",
        ("foto", "evidencia", "imagen", "camara", "galeria"),
        ("como subo fotos", "puedo tomar foto", "cuantas fotos admite", "adjuntar imagen"),
    ),
    FAQEntry(
        "uso_006",
        "ver_notificaciones",
        "uso_sistema",
        "Donde veo mis notificaciones?",
        "En la app entra a Alertas. Alli veras avisos administrativos, cambios de estado e incidentes prioritarios que te correspondan. En el panel web tambien existe una seccion de Notificaciones para usuarios operativos.",
        ("notificaciones", "alertas", "avisos", "campana"),
        ("donde estan las alertas", "como veo avisos", "no veo notificaciones", "que significa la campana"),
    ),
    FAQEntry(
        "uso_007",
        "abrir_notificacion",
        "uso_sistema",
        "Que pasa al tocar una notificacion?",
        "Si la notificacion esta relacionada con un incidente, CommuSafe abre el detalle del caso permitido para tu rol. Si es un aviso, muestra el contenido del comunicado.",
        ("abrir", "notificacion", "detalle", "aviso", "incidente"),
        ("le doy a una alerta", "abrir aviso", "tocar notificacion", "ver notificacion completa"),
    ),
    FAQEntry(
        "uso_008",
        "editar_perfil",
        "uso_sistema",
        "Como actualizo mi telefono o nombre?",
        "Desde Perfil puedes editar tus datos personales habilitados. Mantener el telefono actualizado ayuda a vigilancia y administracion a contactarte cuando exista una novedad.",
        ("perfil", "telefono", "nombre", "editar", "datos"),
        ("cambiar celular", "editar mis datos", "actualizar perfil", "poner mi numero"),
    ),
    FAQEntry(
        "uso_009",
        "cambiar_foto_perfil",
        "uso_sistema",
        "Como cambio mi foto de perfil?",
        "Entra a Perfil y toca el avatar. Puedes tomar una foto o elegir una imagen de galeria. La foto queda visible para facilitar identificacion en el sistema.",
        ("foto", "perfil", "avatar", "galeria", "camara"),
        ("cambiar avatar", "subir foto de perfil", "poner foto", "actualizar imagen"),
    ),
    FAQEntry(
        "uso_010",
        "ajustes_visuales",
        "uso_sistema",
        "Para que sirven los ajustes visuales?",
        "Los ajustes permiten cambiar color principal, contraste, tamano de texto, idioma y preferencias visuales para mejorar accesibilidad y comodidad de uso.",
        ("ajustes", "color", "contraste", "texto", "idioma"),
        ("cambiar color", "aumentar letra", "modo contraste", "configurar idioma"),
    ),
    FAQEntry(
        "uso_011",
        "idioma_app",
        "uso_sistema",
        "La app permite cambiar idioma?",
        "La app incluye ajustes de idioma entre espanol e ingles para textos principales de interfaz. Si una etiqueta no cambia, debe reportarse como mejora de traduccion.",
        ("idioma", "ingles", "espanol", "traduccion"),
        ("poner en ingles", "cambiar lenguaje", "la app sigue en espanol", "idioma de la app"),
    ),
    FAQEntry(
        "uso_012",
        "cerrar_sesion",
        "uso_sistema",
        "Como cierro sesion?",
        "En la app entra a Perfil y usa Cerrar sesion. En el panel web el boton aparece en el sidebar, incluyendo la version responsive movil.",
        ("logout", "cerrar", "sesion", "salir"),
        ("salir de la cuenta", "cerrar mi usuario", "desloguearme", "cerrar sesion"),
    ),
    FAQEntry(
        "uso_013",
        "chat_persistente",
        "uso_sistema",
        "Se guardan mis conversaciones con el asistente?",
        "Si. Las conversaciones del asistente quedan guardadas por usuario en CommuSafe. Puedes abrir chats anteriores y continuar desde donde quedaste.",
        ("chat", "conversacion", "historial", "asistente", "guardar"),
        ("se guarda el chat", "historial del bot", "recuperar conversacion", "continuar chat"),
    ),
    FAQEntry(
        "uso_014",
        "app_sin_conexion",
        "uso_sistema",
        "Que hago si la app no conecta?",
        "Verifica tu conexion a internet, cierra y abre la app, y vuelve a iniciar sesion si es necesario. Si el problema persiste, reportalo a administracion con captura del mensaje.",
        ("conexion", "internet", "backend", "no conecta", "error"),
        ("no carga nada", "no conecta con backend", "error de red", "se queda cargando"),
    ),
    FAQEntry(
        "uso_015",
        "contactos_emergencia_app",
        "uso_sistema",
        "Donde estan los contactos de emergencia?",
        "En la app puedes entrar a Emergencias desde los accesos rapidos o el menu. Alli estan los botones para llamar a lineas de apoyo registradas.",
        ("emergencias", "contactos", "llamar", "telefono", "lineas"),
        ("donde llamo", "botones de emergencia", "telefonos importantes", "contactos rapidos"),
    ),
    FAQEntry(
        "inc_001",
        "categoria_seguridad",
        "incidentes",
        "Que incidentes van como Seguridad?",
        "Usa Seguridad para situaciones como ingreso no autorizado, personas sospechosas, cerraduras forzadas, vehiculos no autorizados, dano intencional en accesos o novedades que requieran atencion prioritaria de vigilancia.",
        ("seguridad", "persona", "sospechosa", "cerradura", "ingreso"),
        ("eso es seguridad", "cuando marco seguridad", "persona rara", "cerraduras danadas"),
    ),
    FAQEntry(
        "inc_002",
        "categoria_emergencia",
        "incidentes",
        "Que incidentes van como Emergencia?",
        "Usa Emergencia cuando exista riesgo inmediato: olor a gas, incendio, accidente, persona herida, inundacion critica, corto electrico peligroso o situacion que pueda afectar la vida o integridad.",
        ("emergencia", "gas", "incendio", "herido", "riesgo"),
        ("olor a gas", "hay fuego", "alguien se cayo", "riesgo de vida"),
    ),
    FAQEntry(
        "inc_003",
        "categoria_convivencia",
        "incidentes",
        "Que incidentes van como Convivencia?",
        "Usa Convivencia para ruido, conflictos entre vecinos, uso inadecuado de zonas comunes, molestias por mascotas, visitantes o situaciones repetitivas que afecten la tranquilidad.",
        ("convivencia", "ruido", "vecinos", "mascotas", "fiesta"),
        ("musica alta", "problema con vecino", "pelea de vecinos", "molestia por mascota"),
    ),
    FAQEntry(
        "inc_004",
        "categoria_infraestructura",
        "incidentes",
        "Que incidentes van como Infraestructura?",
        "Usa Infraestructura para luminarias apagadas, puertas con falla, citofonos, cerraduras comunes, pasillos, zonas verdes, limpieza, goteras o danos en elementos comunes.",
        ("infraestructura", "luz", "puerta", "citofono", "mantenimiento"),
        ("poste apagado", "dano comun", "puerta mala", "luz danada"),
    ),
    FAQEntry(
        "inc_005",
        "prioridad_automatica",
        "incidentes",
        "Como calcula CommuSafe la prioridad?",
        "La prioridad se calcula automaticamente por categoria en backend: Emergencia y Seguridad son Alta, Convivencia es Media e Infraestructura es Baja. No la define el usuario ni la IA.",
        ("prioridad", "alta", "media", "baja", "categoria"),
        ("quien decide prioridad", "por que sale alta", "como sabe si es bajo", "la ia clasifica"),
    ),
    FAQEntry(
        "inc_006",
        "estado_registrado",
        "incidentes",
        "Que significa Registrado?",
        "Registrado significa que el reporte fue recibido por CommuSafe y esta pendiente de revision o asignacion por vigilancia o administracion.",
        ("registrado", "estado", "pendiente", "recibido"),
        ("sale registrado", "que es registrado", "pendiente de revisar", "apenas lo envie"),
    ),
    FAQEntry(
        "inc_007",
        "estado_en_proceso",
        "incidentes",
        "Que significa En proceso?",
        "En proceso indica que un responsable operativo ya esta revisando o atendiendo el incidente. El historial muestra quien cambio el estado y el comentario asociado.",
        ("proceso", "atendiendo", "responsable", "historial"),
        ("en proceso que quiere decir", "ya lo estan mirando", "lo atiende vigilancia", "seguimiento activo"),
    ),
    FAQEntry(
        "inc_008",
        "estado_resuelto",
        "incidentes",
        "Que significa Resuelto?",
        "Resuelto indica que el responsable marco una solucion o atencion del caso. Puede quedar disponible para revision final o cierre segun el flujo administrativo.",
        ("resuelto", "solucionado", "cerrar", "finalizado"),
        ("ya aparece resuelto", "significa solucionado", "que pasa si esta resuelto", "caso solucionado"),
    ),
    FAQEntry(
        "inc_009",
        "estado_cerrado",
        "incidentes",
        "Que significa Cerrado?",
        "Cerrado significa que el caso quedo finalizado administrativamente, con trazabilidad de fecha, responsable y observaciones cuando aplican.",
        ("cerrado", "final", "cierre", "administrativo"),
        ("caso cerrado", "que es cerrado", "finalizaron reporte", "cerraron mi incidente"),
    ),
    FAQEntry(
        "inc_010",
        "historial_estado",
        "incidentes",
        "Para que sirve el historial del incidente?",
        "El historial deja evidencia de cada cambio de estado, responsable, fecha y comentario. Es inmutable desde la API para mantener trazabilidad.",
        ("historial", "estado", "trazabilidad", "comentario"),
        ("timeline del caso", "quien cambio estado", "ver cambios", "registro de cambios"),
    ),
    FAQEntry(
        "inc_011",
        "limite_evidencias",
        "incidentes",
        "Cuantas evidencias puedo subir?",
        "Puedes adjuntar hasta 3 imagenes por incidente. Ese limite ayuda a mantener reportes claros y evita sobrecargar el sistema.",
        ("evidencias", "fotos", "limite", "imagenes"),
        ("maximo fotos", "cuantas imagenes", "subir mas fotos", "limite de evidencia"),
    ),
    FAQEntry(
        "inc_012",
        "reporte_repetido",
        "incidentes",
        "Que hago si un incidente se repite?",
        "Crea un nuevo reporte o describe en el nuevo incidente que la situacion es recurrente. Incluye fechas, horas y evidencias para facilitar seguimiento.",
        ("repite", "recurrente", "otra vez", "seguimiento"),
        ("volvio a pasar", "pasa todos los dias", "incidente repetido", "otra vez ruido"),
    ),
    FAQEntry(
        "inc_013",
        "redaccion_reporte",
        "incidentes",
        "Como redacto bien un reporte?",
        "Usa un titulo corto, describe hechos verificables, indica lugar exacto, fecha u hora aproximada, evita insultos y adjunta evidencia si la tienes.",
        ("redactar", "descripcion", "titulo", "claro", "respeto"),
        ("que escribo", "como describo", "hacer reporte claro", "titulo del incidente"),
    ),
    FAQEntry(
        "inc_014",
        "reportante_contacto",
        "incidentes",
        "Por que aparece el telefono del reportante?",
        "El telefono ayuda a vigilancia o administracion a contactar al reportante si necesitan ampliar informacion. Solo debe usarse para fines operativos del caso.",
        ("telefono", "reportante", "contacto", "datos"),
        ("por que ven mi numero", "datos del reportante", "contactar residente", "telefono en reporte"),
    ),
    FAQEntry(
        "inc_015",
        "eliminar_incidente",
        "incidentes",
        "Se puede eliminar un incidente?",
        "Solo administracion puede eliminar fisicamente un incidente y debe registrar un motivo. El sistema conserva una auditoria con responsable, fecha e identificador del caso eliminado.",
        ("eliminar", "borrar", "auditoria", "motivo"),
        ("borrar reporte", "quitar incidente", "eliminar caso", "quien puede borrar"),
        ADMIN_ROLE,
    ),
    FAQEntry(
        "not_001",
        "notificacion_incidente_nuevo",
        "notificaciones",
        "Quien recibe notificacion cuando se crea un incidente?",
        "Vigilantes y administradores activos reciben notificacion de incidentes nuevos. Si el incidente es prioridad alta, tambien se avisa a residentes activos, excluyendo a quien lo reporto.",
        ("notificacion", "incidente", "nuevo", "roles", "alta"),
        ("a quien le llega", "quienes reciben alerta", "notifican a todos", "alerta incidente"),
    ),
    FAQEntry(
        "not_002",
        "notificacion_cambio_estado",
        "notificaciones",
        "Quien recibe aviso cuando cambia el estado?",
        "El residente que reporto el incidente recibe una notificacion del cambio de estado. Si hay responsable asignado, tambien puede recibirla.",
        ("estado", "notificacion", "cambio", "residente"),
        ("me avisan si cambia", "alerta de seguimiento", "cambio de estado", "quien recibe avance"),
    ),
    FAQEntry(
        "not_003",
        "avisos_admin",
        "notificaciones",
        "Que son los avisos administrativos?",
        "Son comunicados enviados desde CommuSafe por administracion o vigilancia para informar mantenimiento, convivencia, seguridad, reuniones o instrucciones operativas.",
        ("aviso", "administrativo", "comunicado", "mantenimiento", "notificacion", "alerta"),
        (
            "comunicado oficial",
            "mensaje de administracion",
            "avisos del conjunto",
            "informativo",
            "aviso administrativo en notificaciones",
        ),
    ),
    FAQEntry(
        "not_004",
        "destinatarios_aviso",
        "notificaciones",
        "Se pueden enviar avisos a usuarios especificos?",
        "Si. El modulo de avisos permite seleccionar audiencia por rol o usuarios especificos, respetando los permisos del usuario que crea el aviso.",
        ("destinatarios", "usuarios", "especificos", "roles", "aviso"),
        ("mandar aviso a alguien", "seleccionar residentes", "avisar a varios", "notificar vigilantes"),
        OPERATIVE_ROLES,
    ),
    FAQEntry(
        "not_005",
        "avisos_recurrentes",
        "notificaciones",
        "Se pueden programar avisos recurrentes?",
        "Si. CommuSafe permite avisos programados por dias seleccionados, utiles para recordatorios como basura, mantenimiento o recomendaciones periodicas. Deben tener fecha de finalizacion o estar controlados por administracion.",
        ("programar", "recurrente", "dias", "basura", "aviso"),
        ("repetir aviso", "miercoles y viernes", "recordatorio basura", "programar comunicado"),
        OPERATIVE_ROLES,
    ),
    FAQEntry(
        "not_006",
        "marcar_leida",
        "notificaciones",
        "Como marco una notificacion como leida?",
        "En la app puedes abrir la notificacion o usar la accion disponible para marcarla como leida. En panel web aparece la opcion para usuarios operativos.",
        ("leida", "notificacion", "marcar", "alerta"),
        ("quitar pendiente", "marcar todas", "notificacion leida", "badge de alertas"),
    ),
    FAQEntry(
        "not_007",
        "badge_notificaciones",
        "notificaciones",
        "Que significa el numero rojo de notificaciones?",
        "Indica la cantidad de notificaciones no leidas. El conteo se actualiza al consultar alertas o mediante los refrescos implementados en panel y app.",
        ("badge", "numero", "rojo", "notificaciones"),
        ("numero de alertas", "campana con numero", "pendientes", "contador rojo"),
    ),
    FAQEntry(
        "not_008",
        "push_fcm",
        "notificaciones",
        "Las notificaciones push son reales?",
        "El backend esta preparado para enviar push con Firebase Cloud Messaging cuando el dispositivo tiene token FCM y las credenciales de Firebase estan configuradas.",
        ("firebase", "fcm", "push", "token", "celular"),
        ("llega al celular", "push real", "firebase funciona", "token fcm"),
    ),
    FAQEntry(
        "not_009",
        "fallo_push",
        "notificaciones",
        "Que pasa si falla una notificacion push?",
        "El sistema no interrumpe el flujo principal. Guarda la notificacion interna y registra si el push fue enviado o no, para que el usuario pueda verla dentro de CommuSafe.",
        ("fallo", "push", "interna", "enviada"),
        ("no llego push", "firebase fallo", "igual queda alerta", "notificacion interna"),
    ),
    FAQEntry(
        "not_010",
        "avisos_vigentes_banner",
        "notificaciones",
        "Por que aparece un banner de aviso en incidentes?",
        "Los avisos administrativos o emergencias no leidas de los ultimos dias pueden destacarse en la pantalla de incidentes para que el usuario vea informacion importante.",
        ("banner", "aviso", "vigente", "incidentes"),
        ("comunicado arriba", "banner naranja", "aviso destacado", "alerta en inicio"),
    ),
    FAQEntry(
        "not_011",
        "abrir_aviso_panel",
        "notificaciones",
        "Como se abre una notificacion en el panel web?",
        "En el panel web puedes hacer clic sobre la notificacion. Si esta vinculada a un incidente abre el caso; si es aviso muestra el detalle del comunicado.",
        ("panel", "abrir", "notificacion", "aviso", "incidente", "alerta", "web"),
        (
            "click en notificacion",
            "ver aviso panel",
            "abrir incidente desde alerta",
            "notificaciones web",
            "abrir incidente desde alerta en notificaciones",
        ),
        OPERATIVE_ROLES,
    ),
    FAQEntry(
        "not_012",
        "notificaciones_prioridad_alta",
        "notificaciones",
        "Por que recibo notificacion de un incidente de otro residente?",
        "Si el incidente es prioridad alta, CommuSafe puede notificar a residentes activos por prevencion. Ese incidente no se mezcla en tu lista principal, pero puedes abrirlo desde la notificacion si el sistema lo permite.",
        ("alta", "otro", "residente", "prevencion", "notificacion"),
        ("incidente ajeno", "alerta de otro residente", "por que me llego", "no es mi reporte"),
    ),
    FAQEntry(
        "seg_001",
        "emergencia_inmediata",
        "seguridad",
        "Que hago ante una emergencia inmediata?",
        "Prioriza tu seguridad. Contacta porteria y, si hay riesgo para la vida o integridad, llama a la linea 123. Si puedes hacerlo sin exponerte, registra el incidente en CommuSafe.",
        ("emergencia", "123", "riesgo", "vida", "porteria"),
        ("que hago urgente", "hay peligro", "emergencia real", "riesgo de vida"),
    ),
    FAQEntry(
        "seg_002",
        "olor_gas",
        "seguridad",
        "Que hago si siento olor a gas?",
        "Evita encender interruptores o generar chispas, ventila si es seguro, alejate del punto de riesgo, avisa a porteria y reporta Emergencia en CommuSafe con ubicacion exacta.",
        ("gas", "olor", "emergencia", "ventilar", "porteria"),
        ("huele a gas", "fuga de gas", "olor fuerte", "gas en pasillo"),
    ),
    FAQEntry(
        "seg_003",
        "incendio",
        "seguridad",
        "Que hago si hay incendio o humo?",
        "Alejate del riesgo, avisa a porteria, llama a la linea 123 si hay peligro y reporta Emergencia en CommuSafe cuando sea seguro. No intentes controlar el fuego si te expone.",
        ("incendio", "humo", "fuego", "bomberos", "123"),
        ("hay humo", "conato de incendio", "se quema algo", "llamar bomberos"),
    ),
    FAQEntry(
        "seg_004",
        "persona_sospechosa",
        "seguridad",
        "Que hago si veo una persona sospechosa?",
        "Evita confrontarla. Informa a porteria o vigilancia y registra un incidente de Seguridad con descripcion, ubicacion, hora aproximada y evidencia si es seguro obtenerla.",
        ("persona", "sospechosa", "seguridad", "vigilancia"),
        ("alguien raro", "persona extrana", "sospechoso en zona verde", "persona no autorizada"),
    ),
    FAQEntry(
        "seg_005",
        "cerraduras_forzadas",
        "seguridad",
        "Como reporto cerraduras danadas o forzadas?",
        "Registra un incidente de Seguridad indicando puerta, torre, zona exacta, tipo de dano y fotos. Si afecta acceso inmediato, avisa tambien a vigilancia.",
        ("cerradura", "forzada", "danada", "seguridad", "acceso"),
        ("cerradura vandalizada", "puerta forzada", "dano en chapa", "cerraduras rotas"),
    ),
    FAQEntry(
        "seg_006",
        "camara_vigilancia",
        "seguridad",
        "CommuSafe maneja camaras de vigilancia?",
        "No. CommuSafe no incluye modulo de camaras de vigilancia. Las imagenes del sistema son evidencias fotograficas adjuntadas por usuarios al reportar incidentes.",
        ("camara", "vigilancia", "evidencia", "video"),
        ("ver camaras", "camaras del conjunto", "grabaciones", "video vigilancia"),
    ),
    FAQEntry(
        "seg_007",
        "accidente_persona",
        "seguridad",
        "Que hago si una persona se accidenta?",
        "Si hay lesion o riesgo, pide apoyo inmediato a porteria y llama a la linea 123 si corresponde. Luego registra Emergencia con ubicacion y descripcion para dejar trazabilidad.",
        ("accidente", "herida", "persona", "caida", "123"),
        ("alguien se cayo", "residente herido", "accidente escalera", "necesita ambulancia"),
    ),
    FAQEntry(
        "seg_008",
        "vehiculo_no_autorizado",
        "seguridad",
        "Que hago con un vehiculo no autorizado?",
        "Informa a porteria y registra un incidente de Seguridad o Convivencia segun el caso. Incluye placa visible, ubicacion exacta y evidencia si es seguro.",
        ("vehiculo", "autorizado", "placa", "parqueadero"),
        ("carro desconocido", "moto no autorizada", "vehiculo sospechoso", "placa rara"),
    ),
    FAQEntry(
        "seg_009",
        "control_ingreso",
        "seguridad",
        "Por que vigilancia confirma ingresos?",
        "Vigilancia puede solicitar confirmacion para proteger el conjunto cuando el visitante no esta anunciado, hay ingreso vehicular, datos incompletos o una novedad de seguridad.",
        ("ingreso", "vigilancia", "confirmar", "visitante"),
        ("por que llaman de porteria", "confirmar visita", "autorizar ingreso", "control acceso"),
    ),
    FAQEntry(
        "seg_010",
        "lineas_emergencia",
        "seguridad",
        "Cual es la linea de emergencia general?",
        "Para emergencias en Colombia la linea general es 123. Si existe un telefono interno especifico del conjunto, debe validarse con administracion porque CommuSafe no debe inventar numeros no registrados.",
        ("123", "emergencia", "linea", "telefono"),
        ("numero de emergencia", "a quien llamo", "telefono urgencias", "linea colombia"),
    ),
    FAQEntry(
        "seg_011",
        "evidencia_segura",
        "seguridad",
        "Debo tomar foto de una situacion de seguridad?",
        "Solo si es seguro y no te expone. La prioridad es protegerte. Puedes reportar con descripcion y ubicacion aunque no tengas foto.",
        ("foto", "seguridad", "riesgo", "evidencia"),
        ("tomo foto o no", "evidencia peligrosa", "me expongo", "foto a sospechoso"),
    ),
    FAQEntry(
        "seg_012",
        "emergencia_no_confrontar",
        "seguridad",
        "Debo confrontar a alguien en una emergencia?",
        "No. Evita confrontaciones. Busca un lugar seguro, informa a vigilancia o porteria y usa CommuSafe para dejar el registro cuando sea prudente.",
        ("confrontar", "pelea", "seguridad", "vigilancia"),
        ("me acerco", "enfrentar persona", "pelea directa", "confrontacion"),
    ),
    FAQEntry(
        "adm_001",
        "horario_administracion",
        "administracion",
        "Cual es el horario de administracion?",
        "Segun la informacion registrada en CommuSafe, administracion atiende de lunes a viernes de 8:00 a. m. a 5:00 p. m. y sabados de 8:00 a. m. a 12:00 m.",
        ("horario", "administracion", "atencion", "sabado"),
        ("a que hora atienden", "horario oficina", "administracion abre", "atienden sabados"),
    ),
    FAQEntry(
        "adm_002",
        "pagos_cuotas",
        "administracion",
        "Cuanto debo pagar de administracion?",
        SAFE_ADMIN_CONTACT,
        ("cuota", "pago", "administracion", "valor", "saldo"),
        ("cuanto debo", "valor cuota", "saldo administracion", "pagar administracion"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "adm_003",
        "paz_y_salvo",
        "administracion",
        "Como solicito un paz y salvo?",
        "Puedes solicitar orientacion a administracion indicando nombre, unidad residencial y motivo. CommuSafe no emite valores ni certificados exactos desde el asistente.",
        ("paz", "salvo", "certificado", "administracion"),
        ("necesito paz y salvo", "certificado de pago", "solicitar certificado", "documento administracion"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "adm_004",
        "recibos",
        "administracion",
        "Donde consulto recibos o cartera?",
        SAFE_ADMIN_CONTACT,
        ("recibo", "cartera", "saldo", "cuenta", "pago"),
        ("ver recibo", "estado de cartera", "tengo deuda", "consultar saldo"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "adm_005",
        "actualizar_datos",
        "administracion",
        "Como actualizo mis datos de contacto?",
        "Actualiza telefono o datos disponibles desde Perfil. Si necesitas cambiar datos restringidos, solicita apoyo a administracion para mantener la informacion oficial correcta.",
        ("datos", "contacto", "telefono", "perfil", "actualizar"),
        ("cambiar mis datos", "actualizar contacto", "correo incorrecto", "datos personales"),
    ),
    FAQEntry(
        "adm_006",
        "crear_usuario",
        "administracion",
        "Quien puede crear usuarios?",
        "Solo el administrador desde el panel web puede crear usuarios, asignar rol, activar o desactivar cuentas y editar informacion operativa.",
        ("crear", "usuario", "admin", "rol", "cuenta"),
        ("nuevo usuario", "registrar residente", "crear vigilante", "alta usuario"),
        ADMIN_ROLE,
    ),
    FAQEntry(
        "adm_007",
        "editar_usuario",
        "administracion",
        "Quien puede editar usuarios?",
        "Solo administracion puede editar usuarios desde el panel web. Los usuarios pueden actualizar ciertos datos propios desde Perfil cuando el flujo esta habilitado.",
        ("editar", "usuario", "administrador", "datos"),
        ("modificar residente", "editar vigilante", "cambiar datos usuario", "perfil usuario"),
        ADMIN_ROLE,
    ),
    FAQEntry(
        "adm_008",
        "cambiar_rol",
        "administracion",
        "Quien puede cambiar roles?",
        "El cambio de rol es una accion administrativa. Debe realizarse desde el panel web por un administrador autorizado.",
        ("rol", "cambiar", "administrador", "permisos"),
        ("pasar a vigilante", "hacer administrador", "cambiar residente", "rol usuario"),
        ADMIN_ROLE,
    ),
    FAQEntry(
        "adm_009",
        "dashboard_panel",
        "administracion",
        "Que muestra el dashboard del panel?",
        "El dashboard resume incidentes activos, prioridad alta, resueltos del dia, usuarios activos y casos recientes para seguimiento operativo.",
        ("dashboard", "panel", "metricas", "resumen"),
        ("que veo en dashboard", "metricas panel", "resumen administrativo", "inicio web"),
        OPERATIVE_ROLES,
    ),
    FAQEntry(
        "adm_010",
        "exportar_historial",
        "administracion",
        "Puedo exportar incidentes?",
        "Si. En el panel web puedes exportar el historial filtrado de incidentes a Excel o PDF para soporte administrativo.",
        ("exportar", "excel", "pdf", "historial", "incidentes"),
        ("descargar reporte", "exportar excel", "generar pdf", "historial administrativo"),
        OPERATIVE_ROLES,
    ),
    FAQEntry(
        "adm_011",
        "auditoria_eliminados",
        "administracion",
        "Donde veo incidentes eliminados?",
        "El administrador puede consultar la seccion de incidentes eliminados para revisar auditoria: titulo, responsable, fecha y motivo de eliminacion.",
        ("eliminados", "auditoria", "borrados", "motivo"),
        ("ver borrados", "auditoria eliminacion", "incidentes eliminados", "casos borrados"),
        ADMIN_ROLE,
    ),
    FAQEntry(
        "adm_012",
        "telefono_administracion",
        "administracion",
        "Cual es el telefono de administracion?",
        SAFE_ADMIN_CONTACT,
        ("telefono", "administracion", "contacto", "numero"),
        ("numero administracion", "llamar admin", "contacto oficina", "celular administracion"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "conv_001",
        "ruido_excesivo",
        "convivencia",
        "Que hago si hay ruido excesivo?",
        "Registra un incidente de Convivencia indicando hora, lugar, tipo de ruido, duracion y si es recurrente. Evita confrontaciones y adjunta evidencia si es prudente.",
        ("ruido", "musica", "alto", "noche", "convivencia"),
        ("musica alta", "vecino hace ruido", "ruido de madrugada", "fiesta ruidosa"),
    ),
    FAQEntry(
        "conv_002",
        "horario_descanso",
        "convivencia",
        "Cual es el horario de descanso?",
        "La referencia registrada en CommuSafe es de 10:00 p. m. a 6:00 a. m. Durante ese periodo deben evitarse ruidos o actividades que afecten a otros residentes.",
        ("horario", "descanso", "ruido", "noche"),
        ("hasta que hora musica", "horario silencio", "ruido despues de diez", "descanso vecinos"),
    ),
    FAQEntry(
        "conv_003",
        "conflicto_vecino",
        "convivencia",
        "Que hago si tengo conflicto con un vecino?",
        "Registra hechos concretos con respeto, fecha, lugar y evidencia si existe. Si la situacion escala, busca apoyo de administracion o vigilancia y evita confrontaciones.",
        ("conflicto", "vecino", "convivencia", "respeto"),
        ("problema con vecino", "pelea vecino", "discusion", "maltrato verbal"),
    ),
    FAQEntry(
        "conv_004",
        "fiestas_reuniones",
        "convivencia",
        "Que recomendaciones hay para reuniones o fiestas?",
        "Controla volumen, respeta horarios de descanso, cuida zonas comunes, orienta a visitantes y deja limpio el espacio usado. Si aplica reserva, validala con administracion.",
        ("fiesta", "reunion", "volumen", "horario"),
        ("hacer fiesta", "reunion familiar", "actividad social", "musica en reunion"),
    ),
    FAQEntry(
        "conv_005",
        "zonas_comunes_respeto",
        "convivencia",
        "Como deben usarse las zonas comunes?",
        "Deben usarse con limpieza, respeto, cuidado de elementos comunes y sin afectar la tranquilidad de otros residentes.",
        ("zonas", "comunes", "limpieza", "respeto"),
        ("uso zonas comunes", "cuidar areas", "espacios compartidos", "salon comunal"),
    ),
    FAQEntry(
        "conv_006",
        "basura_horarios",
        "convivencia",
        "Que hago con basuras fuera de horario?",
        "Reporta la situacion como Convivencia o Infraestructura segun el impacto, indicando lugar, hora y evidencia. Los horarios exactos deben validarse con avisos o administracion.",
        ("basura", "horario", "residuos", "limpieza"),
        ("sacan basura mal", "basura en pasillo", "residuos fuera horario", "bolsas tiradas"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "conv_007",
        "comunicacion_respetuosa",
        "convivencia",
        "Como debe ser un reporte de convivencia?",
        "Debe describir hechos, no ataques personales. Usa lenguaje respetuoso, indica fecha, hora, lugar, frecuencia y evidencia disponible.",
        ("reporte", "convivencia", "respeto", "hechos"),
        ("redactar convivencia", "sin insultos", "que poner ruido", "reportar vecino bien"),
    ),
    FAQEntry(
        "conv_008",
        "molestias_recurrentes",
        "convivencia",
        "Como reporto una molestia recurrente?",
        "Indica que es recurrente, registra fechas aproximadas, horarios, lugar, impacto y evidencia. Eso permite a administracion revisar el patron.",
        ("recurrente", "molestia", "varias veces", "patron"),
        ("pasa siempre", "todos los fines de semana", "repite problema", "molestia frecuente"),
    ),
    FAQEntry(
        "conv_009",
        "mascota_ruido",
        "convivencia",
        "Que hago si una mascota hace mucho ruido?",
        "Reporta Convivencia con horario, frecuencia, unidad o zona aproximada si la conoces y evidencia prudente. Evita confrontar al propietario.",
        ("mascota", "ruido", "perro", "ladridos", "norma"),
        (
            "perro ladra mucho",
            "mascota molesta",
            "ladridos noche",
            "animal hace ruido",
            "que norma aplica para mascotas",
            "normas para mascotas",
        ),
    ),
    FAQEntry(
        "conv_010",
        "visitantes_convivencia",
        "convivencia",
        "Que pasa si un visitante incumple normas?",
        "El residente que recibe visitas debe orientarlas. Si hay afectacion, registra un incidente de Convivencia o Seguridad segun el riesgo.",
        ("visitante", "normas", "convivencia", "residentes"),
        ("visita molesta", "visitantes hacen ruido", "invitados incumplen", "problema con visita"),
    ),
    FAQEntry(
        "conv_011",
        "rayados_paredes",
        "convivencia",
        "Como reporto rayados o vandalismo en paredes?",
        "Si parece dano intencional, reportalo como Seguridad; si se trata de mantenimiento o limpieza, puede ir como Infraestructura. Incluye ubicacion y fotos.",
        ("rayados", "pared", "vandalismo", "dano"),
        ("pared rayada", "grafiti", "dano intencional", "rayones en muro"),
    ),
    FAQEntry(
        "conv_012",
        "evitar_confrontacion",
        "convivencia",
        "Debo hablar directamente con el vecino?",
        "Si es seguro y respetuoso puede intentarse dialogo, pero si hay tension, riesgo o repeticion, usa CommuSafe y solicita apoyo de administracion o vigilancia.",
        ("dialogo", "vecino", "confrontacion", "respeto"),
        ("hablo con vecino", "le reclamo", "mejor reporto", "evitar problema"),
    ),
    FAQEntry(
        "vis_001",
        "autorizar_visitante",
        "visitantes",
        "Como autorizo un visitante?",
        "Informa a porteria los datos basicos: nombre, unidad a la que se dirige, motivo, hora aproximada y placa si ingresa con vehiculo. Si el conjunto habilita un canal especifico, usalo.",
        ("visitante", "autorizar", "porteria", "ingreso"),
        ("registrar visita", "autorizar entrada", "avisar visitante", "entrada invitado"),
    ),
    FAQEntry(
        "vis_002",
        "datos_visitante",
        "visitantes",
        "Que datos necesita vigilancia para un visitante?",
        "Nombre, unidad destino, residente que autoriza, motivo, hora aproximada y placa si hay vehiculo. Puede pedir confirmacion adicional por seguridad.",
        ("datos", "visitante", "vigilancia", "placa"),
        ("que piden en porteria", "datos de visita", "info visitante", "confirmar visita"),
    ),
    FAQEntry(
        "vis_003",
        "domiciliarios",
        "visitantes",
        "Como se manejan domiciliarios?",
        "El residente debe estar atento a porteria y confirmar el ingreso o recibir el pedido segun el procedimiento vigente del conjunto.",
        ("domicilio", "domiciliario", "pedido", "porteria"),
        ("pedido de comida", "rappi", "domicilio llega", "autorizar domiciliario"),
    ),
    FAQEntry(
        "vis_004",
        "proveedores",
        "visitantes",
        "Como ingreso proveedores o tecnicos?",
        "Informa previamente tipo de servicio, horario estimado, nombre del proveedor y unidad destino. Para ingreso vehicular, agrega placa si aplica.",
        ("proveedor", "tecnico", "servicio", "ingreso"),
        ("tecnico internet", "proveedor externo", "trabajador entra", "servicio apartamento"),
    ),
    FAQEntry(
        "vis_005",
        "vehiculo_visitante",
        "visitantes",
        "Puede entrar un visitante con vehiculo?",
        "Debe validarse con vigilancia o administracion segun disponibilidad y normas internas. CommuSafe no confirma cupos exactos si no estan registrados.",
        ("vehiculo", "visitante", "parqueadero", "cupo"),
        ("visita con carro", "parqueadero visitante", "entrar moto visitante", "cupo visitantes"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "vis_006",
        "visitante_no_anunciado",
        "visitantes",
        "Que pasa si llega un visitante no anunciado?",
        "Vigilancia puede solicitar confirmacion al residente antes de autorizar ingreso. Si no se confirma, puede restringirse el acceso segun el procedimiento interno.",
        ("visitante", "no anunciado", "confirmacion", "porteria"),
        ("llego sin avisar", "visita no registrada", "porteria llama", "no anuncie visitante"),
    ),
    FAQEntry(
        "parq_001",
        "vehiculo_bloquea",
        "parqueaderos",
        "Que hago si un vehiculo bloquea el paso?",
        "Informa a porteria y registra un incidente con ubicacion exacta, placa visible si es posible y foto si es seguro. La categoria puede ser Convivencia o Seguridad segun el riesgo.",
        ("vehiculo", "bloquea", "paso", "placa"),
        ("carro bloqueando", "moto estorba", "no puedo salir", "bloqueo parqueadero"),
    ),
    FAQEntry(
        "parq_002",
        "parqueadero_asignado",
        "parqueaderos",
        "Que hago si ocupan mi parqueadero?",
        "Reporta la novedad con ubicacion, placa visible y evidencia. Avisa a porteria para gestionar contacto o verificacion inmediata.",
        ("parqueadero", "ocupado", "placa", "asignado"),
        ("se parquearon en mi puesto", "ocuparon mi parqueadero", "mi cupo ocupado", "carro en mi lugar"),
    ),
    FAQEntry(
        "parq_003",
        "dano_vehiculo",
        "parqueaderos",
        "Como reporto dano a un vehiculo en parqueadero?",
        "Registra un incidente de Seguridad o Convivencia segun el caso, indicando lugar, fecha aproximada, placa si aplica y evidencia fotografica disponible.",
        ("dano", "vehiculo", "parqueadero", "rayon"),
        ("rayaron carro", "danaron moto", "golpe en parqueadero", "vehiculo afectado"),
    ),
    FAQEntry(
        "parq_004",
        "circulacion_parqueadero",
        "parqueaderos",
        "Como reporto problemas de circulacion en parqueadero?",
        "Describe el punto exacto, torre o nivel, hora y tipo de obstruccion. Adjunta foto si es seguro y avisa a porteria si impide el paso.",
        ("circulacion", "parqueadero", "obstruccion", "paso"),
        ("no hay paso", "parqueadero bloqueado", "obstruyen via", "calle interna bloqueada"),
    ),
    FAQEntry(
        "mas_001",
        "mascota_correa",
        "mascotas",
        "Las mascotas deben ir con correa?",
        "Segun la informacion registrada, las mascotas deben transitar con correa o control adecuado en zonas comunes para evitar molestias o riesgos.",
        ("mascota", "correa", "zonas", "comunes"),
        ("perro sin correa", "mascota suelta", "llevar mascota", "control mascota"),
    ),
    FAQEntry(
        "mas_002",
        "excrementos_mascota",
        "mascotas",
        "Que hago si no recogen excrementos de mascotas?",
        "Reporta Convivencia indicando lugar, hora aproximada, frecuencia y evidencia si es posible. El reporte debe ser respetuoso y basado en hechos.",
        ("excremento", "mascota", "limpieza", "recoger"),
        ("popo de perro", "no recogen", "suciedad mascota", "heces en zona comun"),
    ),
    FAQEntry(
        "mas_003",
        "mascota_extraviada",
        "mascotas",
        "Como reporto una mascota extraviada?",
        "Crea un aviso o incidente segun el flujo disponible, incluyendo foto, descripcion, ultima ubicacion vista y telefono de contacto actualizado.",
        ("mascota", "extraviada", "perdida", "foto"),
        ("perdi mi perro", "gato perdido", "mascota perdida", "buscar mascota"),
    ),
    FAQEntry(
        "mas_004",
        "mascota_agresiva",
        "mascotas",
        "Que hago si una mascota es agresiva?",
        "Evita acercarte, informa a porteria si hay riesgo y registra un incidente de Convivencia o Seguridad con ubicacion, hora y descripcion.",
        ("mascota", "agresiva", "riesgo", "perro"),
        ("perro agresivo", "mascota ataca", "animal peligroso", "mordio a alguien"),
    ),
    FAQEntry(
        "zc_001",
        "horario_zonas_comunes",
        "zonas_comunes",
        "Cual es el horario de zonas comunes?",
        "La referencia registrada es de 6:00 a. m. a 10:00 p. m., salvo aviso administrativo diferente. Para reservas o condiciones exactas valida con administracion.",
        ("zonas", "comunes", "horario", "reserva"),
        (
            "horario salon",
            "area comun",
            "areas comunes",
            "horarios de areas comunes",
            "cuales son los horarios de las areas comunes",
            "hasta que hora zona comun",
            "usar zonas comunes",
        ),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "zc_002",
        "reservar_zona_comun",
        "zonas_comunes",
        "Como reservo una zona comun?",
        "CommuSafe puede orientar el proceso, pero la disponibilidad, requisitos y costos deben validarse con administracion porque no hay agenda exacta registrada en el asistente.",
        ("reservar", "zona", "comun", "salon", "disponibilidad"),
        ("reservar salon", "apartar zona comun", "disponible salon", "costo reserva"),
        ALL_ROLES,
        False,
    ),
    FAQEntry(
        "zc_003",
        "dano_zona_comun",
        "zonas_comunes",
        "Como reporto dano en una zona comun?",
        "Crea un incidente de Infraestructura con ubicacion exacta, descripcion del elemento afectado y evidencia fotografica si esta disponible.",
        ("dano", "zona", "comun", "infraestructura"),
        ("dano salon", "elemento comun roto", "reporte zona comun", "mantenimiento area comun"),
    ),
    FAQEntry(
        "zc_004",
        "limpieza_zona_comun",
        "zonas_comunes",
        "Como reporto falta de limpieza?",
        "Registra Infraestructura o Convivencia segun el origen del problema. Indica punto exacto, hora aproximada y evidencia si la tienes.",
        ("limpieza", "zona", "comun", "basura"),
        ("sucio pasillo", "zona comun sucia", "falta aseo", "basura en area comun"),
    ),
    FAQEntry(
        "mant_001",
        "luminaria_apagada",
        "mantenimiento",
        "Como reporto una luminaria apagada?",
        "Crea un incidente de Infraestructura. Indica torre, pasillo, calle interna o punto exacto, y adjunta foto si es posible.",
        ("luminaria", "luz", "apagada", "poste"),
        ("poste apagado", "pasillo oscuro", "luz danada", "sin iluminacion"),
    ),
    FAQEntry(
        "mant_002",
        "citofono_danado",
        "mantenimiento",
        "Como reporto un citofono danado?",
        "Reportalo como Infraestructura indicando unidad, torre o punto donde falla, desde cuando ocurre y si afecta ingreso o comunicacion con porteria.",
        ("citofono", "danado", "comunicacion", "porteria"),
        ("intercomunicador malo", "citofono no sirve", "no llama porteria", "fallo citofono"),
    ),
    FAQEntry(
        "mant_003",
        "puerta_falla",
        "mantenimiento",
        "Como reporto una puerta con falla?",
        "Si es una puerta comun, crea Incidente de Infraestructura; si hay senales de manipulacion o dano intencional, usa Seguridad.",
        ("puerta", "falla", "cerradura", "infraestructura"),
        ("puerta no cierra", "acceso falla", "puerta danada", "cerradura comun"),
    ),
    FAQEntry(
        "mant_004",
        "fuga_agua",
        "mantenimiento",
        "Como reporto una fuga de agua?",
        "Si la fuga afecta zona comun o genera riesgo, reporta Infraestructura con ubicacion exacta, descripcion y foto. Si es critica, avisa tambien a porteria.",
        ("fuga", "agua", "goteo", "infraestructura"),
        ("hay agua", "goteras", "pasillo mojado", "fuga pasillo"),
    ),
    FAQEntry(
        "mant_005",
        "dano_privado_comun",
        "mantenimiento",
        "Cual es la diferencia entre dano privado y comun?",
        "Un dano dentro del apartamento suele gestionarlo el residente. Un dano en pasillos, accesos, zonas verdes, puertas comunes o elementos compartidos puede reportarse en CommuSafe.",
        ("privado", "comun", "dano", "apartamento"),
        ("dano en mi apartamento", "zona comun o privado", "quien arregla", "mantenimiento interno"),
    ),
    FAQEntry(
        "asis_001",
        "alcance_asistente",
        "asistente",
        "Sobre que puede responder CommuBot?",
        "CommuBot responde sobre Remansos del Norte, CommuSafe, incidentes, avisos, convivencia, seguridad, administracion general y uso de la plataforma. No responde temas externos.",
        ("commubot", "asistente", "alcance", "preguntar"),
        ("que puedo preguntar", "para que sirve bot", "asistente virtual", "commubot ayuda"),
    ),
    FAQEntry(
        "asis_002",
        "pregunta_fuera_contexto",
        "asistente",
        "Puede CommuBot responder temas externos?",
        "No. CommuBot solo apoya consultas relacionadas con Remansos del Norte y CommuSafe. Para otros temas debes usar una fuente externa adecuada.",
        ("externo", "fuera", "tema", "contexto"),
        ("pregunta cualquiera", "hablar de deportes", "tema externo", "politica o noticias"),
    ),
    FAQEntry(
        "asis_003",
        "no_inventar",
        "asistente",
        "Que pasa si CommuBot no sabe algo?",
        "Debe indicarlo de forma clara y recomendar validar con administracion. No debe inventar telefonos, valores, sanciones, horarios especiales ni decisiones administrativas.",
        ("no sabe", "inventar", "validar", "administracion"),
        ("si no tiene dato", "respuesta desconocida", "dato exacto", "no encuentra informacion"),
    ),
    FAQEntry(
        "asis_004",
        "modo_hibrido",
        "asistente",
        "El asistente usa siempre IA generativa?",
        "No. Primero intenta responder con conocimiento local verificado. Solo usa IA generativa como respaldo controlado cuando la consulta no tiene una coincidencia local suficiente.",
        ("ia", "local", "gemini", "tokens", "hibrido"),
        ("consume tokens", "usa gemini siempre", "modo local", "como responde el bot"),
    ),
    FAQEntry(
        "asis_005",
        "privacidad_chat",
        "asistente",
        "Otros usuarios pueden ver mis chats?",
        "No. Las conversaciones del asistente estan asociadas al usuario autenticado. Cada usuario solo puede listar, abrir o eliminar sus propias conversaciones.",
        ("privacidad", "chat", "conversacion", "usuario"),
        ("quien ve mi chat", "otro residente ve", "historial privado", "seguridad conversaciones"),
    ),
    FAQEntry(
        "asis_006",
        "metricas_asistente",
        "asistente",
        "Que registra el sistema sobre respuestas del asistente?",
        "El backend registra modo de respuesta, proveedor, confianza, intencion detectada, latencia y metadatos tecnicos para medir cobertura local, calidad y ahorro de uso de IA externa.",
        ("metricas", "log", "latencia", "confianza", "modo"),
        ("auditoria asistente", "como miden respuestas", "registro del bot", "ahorro tokens"),
        OPERATIVE_ROLES,
    ),
    FAQEntry(
        "asis_007",
        "aclaracion_asistente",
        "asistente",
        "Por que el asistente pide aclaracion?",
        "Cuando varias preguntas posibles tienen confianza similar, CommuBot pide aclaracion o presenta opciones para evitar responder algo incorrecto.",
        ("aclaracion", "duda", "confianza", "opciones"),
        ("por que pregunta otra vez", "no entendio", "me da opciones", "respuesta ambigua"),
    ),
)


def get_entries_for_role(role: str | None, *, only_active: bool = True) -> tuple[FAQEntry, ...]:
    """Filtra entradas segun rol del usuario."""

    role = (role or "RESIDENTE").upper()
    return tuple(
        entry
        for entry in FAQ_ENTRIES
        if role in entry.allowed_roles and (not only_active or entry.is_active())
    )


def knowledge_summary() -> dict[str, int]:
    """Devuelve conteos utiles para health checks y documentacion."""

    categories = {entry.category for entry in FAQ_ENTRIES}
    verified = sum(1 for entry in FAQ_ENTRIES if entry.verified)
    active = sum(1 for entry in FAQ_ENTRIES if entry.is_active())
    pending = len(FAQ_ENTRIES) - verified
    return {
        "total_faq": len(FAQ_ENTRIES),
        "categorias": len(categories),
        **taxonomy_summary(),
        "verificadas": verified,
        "pendientes_validacion": pending,
        "vigentes": active,
        "vencidas": len(FAQ_ENTRIES) - active,
        "estado_verificacion": {
            VERIFICATION_VERIFIED: verified,
            VERIFICATION_PENDING_ADMIN: pending,
        },
    }
