# Generated by Django 4.2 on 2026-04-21 19:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import incidentes.models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(choices=[('SEGURIDAD', 'Seguridad'), ('CONVIVENCIA', 'Convivencia'), ('INFRAESTRUCTURA', 'Infraestructura'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('prioridad', models.CharField(choices=[('ALTA', 'Alta'), ('MEDIA', 'Media'), ('BAJA', 'Baja')], editable=False, max_length=10)),
                ('estado', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='REGISTRADO', max_length=20)),
                ('ubicacion_referencia', models.CharField(blank=True, max_length=255)),
                ('fecha_reporte', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('fecha_cierre', models.DateTimeField(blank=True, null=True)),
                ('observaciones_cierre', models.TextField(blank=True)),
                ('atendido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_atendidos', to=settings.AUTH_USER_MODEL)),
                ('reportado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_reportados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente',
                'verbose_name_plural': 'Incidentes',
                'ordering': ('-fecha_reporte',),
            },
        ),
        migrations.CreateModel(
            name='HistorialEstado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('estado_anterior', models.CharField(blank=True, choices=[('REGISTRADO', 'Registrado'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], default='', max_length=20)),
                ('estado_nuevo', models.CharField(choices=[('REGISTRADO', 'Registrado'), ('EN_PROCESO', 'En proceso'), ('RESUELTO', 'Resuelto'), ('CERRADO', 'Cerrado')], max_length=20)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('comentario', models.TextField(blank=True)),
                ('cambiado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cambios_estado_incidentes', to=settings.AUTH_USER_MODEL)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Historial de estado',
                'verbose_name_plural': 'Historiales de estado',
                'ordering': ('-fecha_cambio',),
            },
        ),
        migrations.CreateModel(
            name='EvidenciaIncidente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imagen', models.ImageField(upload_to=incidentes.models.ruta_evidencia_incidente)),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha_subida', models.DateTimeField(auto_now_add=True)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Evidencia de incidente',
                'verbose_name_plural': 'Evidencias de incidentes',
                'ordering': ('-fecha_subida',),
            },
        ),
    ]
