# Generated by Django 4.2 on 2026-04-29 21:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('incidentes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidenteEliminado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('incidente_id', models.UUIDField(db_index=True)),
                ('titulo', models.CharField(max_length=150)),
                ('fecha_eliminacion', models.DateTimeField(auto_now_add=True)),
                ('motivo', models.TextField()),
                ('eliminado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidentes_eliminados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Incidente eliminado',
                'verbose_name_plural': 'Incidentes eliminados',
                'ordering': ('-fecha_eliminacion',),
            },
        ),
    ]
