# Generated by Django 4.2 on 2026-05-24 22:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversacionAsistente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(default='Nueva conversación', max_length=90)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversaciones_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Conversación del asistente',
                'verbose_name_plural': 'Conversaciones del asistente',
                'ordering': ('-fecha_actualizacion',),
            },
        ),
        migrations.CreateModel(
            name='MensajeAsistente',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rol', models.CharField(choices=[('USUARIO', 'Usuario'), ('ASISTENTE', 'Asistente')], max_length=12)),
                ('contenido', models.TextField()),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensajes', to='asistente.conversacionasistente')),
            ],
            options={
                'verbose_name': 'Mensaje del asistente',
                'verbose_name_plural': 'Mensajes del asistente',
                'ordering': ('fecha_creacion',),
            },
        ),
    ]
