# Generated by Django 4.2 on 2026-06-05 20:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistente', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsistenteRespuestaLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mensaje', models.TextField()),
                ('modo', models.CharField(choices=[('local', 'Local'), ('semantica', 'Semantica'), ('aclaracion', 'Aclaracion'), ('ia', 'IA generativa'), ('segura', 'Respuesta segura'), ('fallback', 'Fallback'), ('error', 'Error')], db_index=True, max_length=20)),
                ('proveedor', models.CharField(blank=True, max_length=40)),
                ('modelo', models.CharField(blank=True, max_length=80)),
                ('intencion', models.CharField(blank=True, db_index=True, max_length=120)),
                ('categoria', models.CharField(blank=True, max_length=80)),
                ('metodo', models.CharField(blank=True, max_length=80)),
                ('confianza', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('latencia_ms', models.PositiveIntegerField(default=0)),
                ('tokens_entrada', models.PositiveIntegerField(blank=True, null=True)),
                ('tokens_salida', models.PositiveIntegerField(blank=True, null=True)),
                ('requiere_validacion', models.BooleanField(default=False)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('conversacion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_respuesta', to='asistente.conversacionasistente')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs_asistente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de respuesta del asistente',
                'verbose_name_plural': 'Logs de respuestas del asistente',
                'ordering': ('-fecha_creacion',),
            },
        ),
        migrations.AddIndex(
            model_name='asistenterespuestalog',
            index=models.Index(fields=['modo', 'fecha_creacion'], name='asistente_a_modo_1f2192_idx'),
        ),
        migrations.AddIndex(
            model_name='asistenterespuestalog',
            index=models.Index(fields=['intencion', 'fecha_creacion'], name='asistente_a_intenci_6b2e39_idx'),
        ),
    ]
