# Generated by Django 4.2 on 2026-06-09 00:48

import asistente.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('asistente', '0002_asistenterespuestalog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntradaConocimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('codigo', models.SlugField(max_length=120, unique=True)),
                ('pregunta', models.CharField(max_length=300)),
                ('respuesta', models.TextField()),
                ('categoria', models.CharField(db_index=True, max_length=80)),
                ('intencion_principal', models.CharField(db_index=True, max_length=120)),
                ('subintencion', models.CharField(blank=True, max_length=120)),
                ('palabras_clave', models.JSONField(blank=True, default=asistente.models.lista_vacia)),
                ('variaciones', models.JSONField(blank=True, default=asistente.models.lista_vacia)),
                ('roles_permitidos', models.JSONField(default=asistente.models.roles_conocimiento_default)),
                ('estado', models.CharField(choices=[('BORRADOR', 'Borrador'), ('EN_REVISION', 'En revision'), ('APROBADA', 'Aprobada'), ('INACTIVA', 'Inactiva'), ('RECHAZADA', 'Rechazada')], db_index=True, default='BORRADOR', max_length=20)),
                ('vigente_desde', models.DateField(default=django.utils.timezone.localdate)),
                ('vigente_hasta', models.DateField(blank=True, null=True)),
                ('fuente', models.CharField(blank=True, max_length=240)),
                ('nota_cambio', models.CharField(blank=True, max_length=300)),
                ('version', models.PositiveIntegerField(default=1, editable=False)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, db_index=True)),
                ('actualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conocimiento_actualizado', to=settings.AUTH_USER_MODEL)),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conocimiento_aprobado', to=settings.AUTH_USER_MODEL)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conocimiento_creado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Entrada de conocimiento',
                'verbose_name_plural': 'Base de conocimiento',
                'ordering': ('categoria', 'pregunta'),
            },
        ),
        migrations.CreateModel(
            name='VersionEntradaConocimiento',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.PositiveIntegerField()),
                ('datos', models.JSONField(default=dict)),
                ('fecha_cambio', models.DateTimeField(auto_now_add=True)),
                ('cambiado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='versiones_conocimiento', to=settings.AUTH_USER_MODEL)),
                ('entrada', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historial_versiones', to='asistente.entradaconocimiento')),
            ],
            options={
                'verbose_name': 'Version de conocimiento',
                'verbose_name_plural': 'Versiones de conocimiento',
                'ordering': ('-fecha_cambio',),
            },
        ),
        migrations.CreateModel(
            name='ConsultaSinRespuesta',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('huella', models.CharField(max_length=64)),
                ('rol', models.CharField(db_index=True, max_length=20)),
                ('consulta_muestra', models.TextField()),
                ('consulta_normalizada', models.TextField()),
                ('cantidad', models.PositiveIntegerField(db_index=True, default=1)),
                ('confianza_maxima', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True)),
                ('intencion_sugerida', models.CharField(blank=True, max_length=120)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_REVISION', 'En revision'), ('CONVERTIDA', 'Convertida en conocimiento'), ('DESCARTADA', 'Descartada')], db_index=True, default='PENDIENTE', max_length=20)),
                ('fecha_primera_consulta', models.DateTimeField(auto_now_add=True)),
                ('fecha_ultima_consulta', models.DateTimeField(auto_now=True, db_index=True)),
                ('entrada_generada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_origen', to='asistente.entradaconocimiento')),
                ('revisado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas_conocimiento_revisadas', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consulta sin respuesta',
                'verbose_name_plural': 'Consultas sin respuesta',
                'ordering': ('-cantidad', '-fecha_ultima_consulta'),
            },
        ),
        migrations.AddConstraint(
            model_name='versionentradaconocimiento',
            constraint=models.UniqueConstraint(fields=('entrada', 'version'), name='uq_conocimiento_entrada_version'),
        ),
        migrations.AddIndex(
            model_name='entradaconocimiento',
            index=models.Index(fields=['estado', 'fecha_actualizacion'], name='asistente_e_estado_2b5c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='entradaconocimiento',
            index=models.Index(fields=['categoria', 'estado'], name='asistente_e_categor_b23b66_idx'),
        ),
        migrations.AddIndex(
            model_name='consultasinrespuesta',
            index=models.Index(fields=['estado', 'cantidad'], name='asistente_c_estado_2b15e3_idx'),
        ),
        migrations.AddConstraint(
            model_name='consultasinrespuesta',
            constraint=models.UniqueConstraint(fields=('huella', 'rol'), name='uq_consulta_sin_respuesta_huella_rol'),
        ),
    ]
