# Generated by Django 4.2 on 2026-05-24 18:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notificaciones', '0002_alter_notificacion_schema'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvisoProgramado',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('titulo', models.CharField(max_length=150)),
                ('cuerpo', models.TextField()),
                ('tipo', models.CharField(choices=[('INCIDENTE_NUEVO', 'Incidente nuevo'), ('CAMBIO_ESTADO', 'Cambio de estado'), ('AVISO_ADMIN', 'Aviso administrativo'), ('EMERGENCIA', 'Emergencia')], max_length=20)),
                ('audiencia', models.CharField(max_length=20)),
                ('dias_semana', models.CharField(max_length=20)),
                ('fecha_inicio', models.DateField(default=django.utils.timezone.localdate)),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('ultimo_envio', models.DateField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='avisos_programados_creados', to=settings.AUTH_USER_MODEL)),
                ('destinatarios', models.ManyToManyField(blank=True, related_name='avisos_programados_asignados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Aviso programado',
                'verbose_name_plural': 'Avisos programados',
                'ordering': ('-activo', 'titulo'),
            },
        ),
    ]
