# Generated by Django 4.2 on 2026-06-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0003_avisoprogramado'),
    ]

    operations = [
        migrations.AddField(
            model_name='notificacion',
            name='deduplicacion_clave',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
    ]
