# Generated by Django 4.2 on 2026-06-09 21:43

from django.db import migrations


def limpiar_duplicados_recientes(apps, schema_editor):
    Notificacion = apps.get_model("notificaciones", "Notificacion")
    ultima_por_contenido = {}
    ventana_segundos = 5 * 60

    for notificacion in Notificacion.objects.order_by("fecha_envio").iterator(chunk_size=1000):
        clave = (
            notificacion.destinatario_id,
            notificacion.titulo,
            notificacion.cuerpo,
            notificacion.tipo,
            notificacion.incidente_relacionado_id,
        )
        conservada = ultima_por_contenido.get(clave)
        if conservada is None:
            ultima_por_contenido[clave] = notificacion
            continue

        diferencia = (notificacion.fecha_envio - conservada.fecha_envio).total_seconds()
        if diferencia > ventana_segundos:
            ultima_por_contenido[clave] = notificacion
            continue

        campos_actualizados = []
        if notificacion.leida and not conservada.leida:
            conservada.leida = True
            campos_actualizados.append("leida")
        if notificacion.enviada_push and not conservada.enviada_push:
            conservada.enviada_push = True
            campos_actualizados.append("enviada_push")
        if campos_actualizados:
            conservada.save(update_fields=campos_actualizados)
        notificacion.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('notificaciones', '0004_notificacion_deduplicacion_clave'),
    ]

    operations = [
        migrations.RunPython(limpiar_duplicados_recientes, migrations.RunPython.noop),
    ]
