# Generated by Django 4.2 on 2026-04-29 17:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import usuarios.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PasswordResetToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, default=usuarios.models.generar_token_reset_password, editable=False, max_length=128, unique=True)),
                ('creado', models.DateTimeField(auto_now_add=True)),
                ('usado', models.BooleanField(default=False)),
                ('expira', models.DateTimeField(default=usuarios.models.expira_token_reset_password)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens_reset_password', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Token de recuperacion de contrasena',
                'verbose_name_plural': 'Tokens de recuperacion de contrasena',
                'ordering': ('-creado',),
            },
        ),
    ]
